routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([
  'middleware' => 'auth',
  'namespace' => 'Admin',
  'prefix' => 'system/role',
  'as' => 'roles.',
], function () {
    Route::get('/', ['as' => 'show', 'uses' => 'AdminRoleController@index']);

    Route::get('/create',
      ['as' => 'formcreate', 'uses' => 'AdminRoleController@showformcreate']);

    Route::post('/create',
      ['as' => 'create', 'uses' => 'AdminRoleController@create']);

    Route::get('/update/{id}',
      ['as' => 'formupdate', 'uses' => 'AdminRoleController@showformupdate']);

    Route::post('/update',
      ['as' => 'update', 'uses' => 'AdminRoleController@update']);

    Route::post('/delete',
      ['as' => 'delete', 'uses' => 'AdminRoleController@delete']);
});

Route::group([
  'middleware' => 'auth',
  'namespace' => 'Admin',
  'prefix' => 'system/permission',
  'as' => 'permissions.',
], function () {
    Route::get('/',
      ['as' => 'show', 'uses' => 'AdminPermissionController@index']);

    Route::get('/create',
      [
        'as' => 'formcreate',
        'uses' => 'AdminPermissionController@showformcreate',
      ]);

    Route::post('/create',
      ['as' => 'create', 'uses' => 'AdminPermissionController@create']);

    Route::get('/update/{id}',
      [
        'as' => 'formupdate',
        'uses' => 'AdminPermissionController@showformupdate',
      ]);

    Route::post('/update',
      ['as' => 'update', 'uses' => 'AdminPermissionController@update']);

    Route::post('/delete',
      ['as' => 'delete', 'uses' => 'AdminPermissionController@delete']);
});

Route::group([
  'middleware' => 'auth',
  'namespace' => 'Admin',
  'prefix' => 'system/user',
  'as' => 'users.',
], function () {
    Route::get('/',
      ['as' => 'show', 'uses' => 'AdminUserController@index']);

    //    Route::get('/create',
    //      [
    //        'as' => 'formcreate',
    //        'uses' => 'AdminUserController@showformcreate',
    //      ]);
    //
    //    Route::post('/create',
    //      ['as' => 'create', 'uses' => 'AdminUserController@create']);

    Route::get('/update/{id}',
      [
        'as' => 'formupdate',
        'uses' => 'AdminUserController@showformupdate',
      ]);

    Route::post('/update',
      ['as' => 'update', 'uses' => 'AdminUserController@update']);

    Route::post('/delete',
      ['as' => 'delete', 'uses' => 'AdminUserController@delete']);
});

Route::group([
  'middleware' => 'auth',
  'namespace' => 'Admin',
  'prefix' => 'yandex/webmaster',
  'as' => 'webmasters.',
], function () {
    Route::get('/',
      ['as' => 'show', 'uses' => 'AdminYandexWebmasterController@index']);

    Route::get('/create',
      [
        'as' => 'formcreate',
        'uses' => 'AdminYandexWebmasterController@showformcreate',
      ]);

    Route::post('/create',
      ['as' => 'create', 'uses' => 'AdminYandexWebmasterController@create']);


    //    Route::get('/update/{id}',
    //      [
    //        'as' => 'formupdate',
    //        'uses' => 'AdminUserController@showformupdate',
    //      ]);
    //
    //    Route::post('/update',
    //      ['as' => 'update', 'uses' => 'AdminUserController@update']);
    //
    Route::post('/delete',
      ['as' => 'delete', 'uses' => 'AdminYandexWebmasterController@delete']);

    Route::get('/callback',
      [
        'as' => 'callback',
        'uses' => 'AdminYandexWebmasterController@callback',
      ]);
});
Route::group([
  'middleware' => 'auth',
  'as' => 'home',
], function () {
    Route::get('/', 'HomeController@index')->name('home');
});

Route::group([
  'middleware' => 'auth',
  'namespace' => 'Admin',
  'prefix' => 'yandex/direct',
  'as' => 'directs.',
], function () {
    Route::get('/',
      ['as' => 'show', 'uses' => 'AdminYandexDirectController@index']);

    Route::get('/create',
      [
        'as' => 'formcreate',
        'uses' => 'AdminYandexDirectController@showformcreate',
      ]);

    Route::post('/create',
      ['as' => 'create', 'uses' => 'AdminYandexDirectController@create']);

    Route::post('/refresh',
      [
        'as' => 'refresh',
        'uses' => 'AdminYandexDirectController@showformrefresh',
      ]);

    Route::post('/refresh-token',
      [
        'as' => 'refresh.token',
        'uses' => 'AdminYandexDirectController@refreshToken',
      ]);

    Route::get('/check-refresh',
      [
        'as' => 'check.refresh',
        'uses' => 'AdminYandexDirectController@checkshowformrefresh',
      ]);

    Route::post('/startrefresh',
      [
        'as' => 'startrefresh',
        'uses' => 'AdminYandexDirectController@refresh',
      ]);
    //    Route::get('/update/{id}',
    //      [
    //        'as' => 'formupdate',
    //        'uses' => 'AdminUserController@showformupdate',
    //      ]);
    //
    //    Route::post('/update',
    //      ['as' => 'update', 'uses' => 'AdminUserController@update']);
    //
    Route::post('/archive',
      ['as' => 'archive', 'uses' => 'AdminYandexDirectController@archive']);

    Route::get('/getarchive',
      ['as' => 'getarchive', 'uses' => 'AdminYandexDirectController@index']);

    Route::get('/statistics',
      [
        'as' => 'statistics',
        'uses' => 'AdminYandexDirectController@statistics',
      ]);

    Route::post('/getstatistic',
      [
        'as' => 'getstatistic',
        'uses' => 'AdminYandexDirectController@getstatistic',
      ]);

    Route::get('/callback',
      [
        'as' => 'callback',
        'uses' => 'AdminYandexDirectController@callback',
      ]);
});



Auth::routes();

resources/views/admin/yandex/direct/Direct.blade.php
@extends('layouts.app')
@section('styles')
    <script src="{{ mix('/js/pages_projects_list.js') }}"></script>

    <!-- SweetAlerts -->
    <link rel="stylesheet" href="{{ mix('/vendor/libs/bootstrap-sweetalert/bootstrap-sweetalert.css') }}">
@endsection

@section('scripts')

    <!-- SweetAlerts -->
    <script src="{{ mix('/vendor/libs/bootbox/bootbox.js') }}"></script>
    <script src="{{ mix('/vendor/libs/bootstrap-sweetalert/bootstrap-sweetalert.js') }}"></script>
    <script src="{{ mix('/js/ui_modals.js') }}"></script>
@endsection



@section('content')


    <h4 class="d-flex justify-content-between align-items-center w-100 font-weight-bold py-3 mb-4">
        <div>Акаунты в Yandex Direct</div>
        <div>
            <a href="{{ URL::route('directs.getarchive') }}" class="btn btn-sm btn-outline-danger">
                <span class="ion ion-ios-trash"></span>&nbsp; Архив
            </a>
            <a href="{{ URL::route('directs.statistics') }}" class="btn btn-sm btn-outline-primary">
                <span class="ion ion-ios-trending-up"></span>&nbsp; Статистика
            </a>
            <a href="{{ URL::route('directs.formcreate') }}" class="btn btn-sm btn-outline-success">
                <span class="ion ion-md-add"></span>&nbsp; Добавить аккаунт
            </a>
        </div>

    </h4>


    @if( session('status'))
        <div class="alert alert-dark-{{session('type')}} alert-dismissible fade show">
            <button type="button" class="close" data-dismiss="alert">×</button>
            {{ session('status') }}<br>
        </div>
    @endif






    <div class="row">

        @foreach ($userDirects as $userDirect)
            <div class="col-sm-6 col-xl-12" id="{{ $userDirect->id }}">
                <div class="card mb-4 border-{{ $campaignStatus[$userDirect->user_login] }}">

                    <div class="card-body d-flex justify-content-between align-items-start pb-3">
                        <div>
                            <a href="#company-faq-{{ $userDirect->id }}"
                               class="text-dark text-big font-weight-semibold collapsed" data-toggle="collapse"
                               aria-expanded="false">{{ $userDirect->token_name }}</a>
                            <span class="badge badge-{{ $campaignStatus[$userDirect->user_login] }} align-text-bottom ml-1">{{ $campaignStatus[$userDirect->user_login] == 'success' ? 'Всё хорошо' : 'Аларм блять'}}</span>
                            <span class="badge badge-{{ $campaignStatus[$userDirect->user_login] }} align-text-bottom ml-1">{{ $money[$userDirect->user_login] > 0 ? 'Осталось: ' . $money[$userDirect->user_login] . ' Руб.' : 'Осталось: ' . $money[$userDirect->user_login] . ' Руб.'}}</span>
                            <div class="text-muted small mt-1">{{$userDirect->user_login}}@yandex.ru</div>
                        </div>
                        <div class="btn-group project-actions">
                            <button type="button"
                                    class="btn btn-sm btn-default icon-btn borderless btn-round md-btn-flat dropdown-toggle hide-arrow"
                                    data-toggle="dropdown">
                                <i class="ion ion-ios-more"></i>
                            </button>

                            <div class="dropdown-menu dropdown-menu-right">
                                <input type="hidden" id="token" value="<?php echo csrf_token(); ?>">
                                <button class="dropdown-item delete" data-element-id="{{ $userDirect->id }}"
                                        data-method-post="archive"
                                        data-title-post="Вы точно хотите архивировать аккаунт?" data-text-post=" "
                                        onclick="return false;">Архивировать
                                </button>

                                {!! Form::open(['route' => 'directs.refresh.token']) !!}

                                <div class="form-group">
                                    {!! Form::hidden('token_id', $userDirect->id) !!}
                                </div>
                                {!! Form::submit('Обновить токен', ['class' => 'dropdown-item']) !!}

                                {!! Form::close() !!}

                                {{--Форма перезагрузки Р.К.--}}
                                {!! Form::open(['route' => 'directs.refresh']) !!}

                                <div class="form-group">
                                    {!! Form::hidden('step_one', '1') !!}
                                </div>
                                <div class="form-group">
                                    {!! Form::hidden('token_id', $userDirect->id) !!}
                                </div>
                                <div class="form-group">
                                    {!! Form::hidden('token_name', $userDirect->token_name) !!}
                                </div>
                                <div class="form-group">
                                    {!! Form::hidden('token', $userDirect->token) !!}
                                </div>
                                <div class="form-group">
                                    {!! Form::hidden('user_login', $userDirect->user_login) !!}
                                </div>

                                {!! Form::submit('Перезапустить', ['class' => 'dropdown-item']) !!}

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                    <div class="progress rounded-0" style="height: 3px;">
                        <div class="progress-bar @if($money[$userDirect->user_login] == 0) bg-danger @elseif($money[$userDirect->user_login] < 600) bg-warning @else bg-success @endif"
                             style="width: {{100 - $money[$userDirect->user_login] / 12000 * 100}}%;"></div>
                    </div>
                    <div class="card-body small pt-2 pb-0">
                        Бюджет израсходаван на <strong>{{round(100 - $money[$userDirect->user_login] / 12000 * 100)}}
                            %</strong>
                    </div>
                    <div class="card-body pb-3 collapse" id="company-faq-{{ $userDirect->id }}">
                        <ul class="list-group">
                            @forelse($Campaigns[$userDirect->user_login] as $Campaign)
                                <li class="list-group-item d-flex justify-content-between align-items-center">{{ $Campaign->Name }}
                                    <span class="badge badge-{{ $Campaign->StatusClarification == 'Идут показы' ? 'success' : 'danger' }}">{{$Campaign->StatusClarification}}</span>
                                </li>
                            @empty
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    Неизвестная ошибка
                                </li>
                            @endforelse
                        </ul>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
@endsection

resources/views/admin/yandex/direct/FormGetStatistics.blade.php
@extends('layouts.app')

@section('styles')

    <link rel="stylesheet" href="{{ mix('vendor/libs/bootstrap-datepicker/bootstrap-datepicker.css') }}">
@endsection

@section('scripts')
    <script src="{{ mix('vendor/libs/bootstrap-datepicker/bootstrap-datepicker.js') }}"></script>
    <script src="{{ mix('js/forms_pickers.js') }}"></script>
@endsection

@section('content')
    <div class="card mb-4">

        <h6 class="card-header">
            Получение статистики </h6>
        <div class="card-body">
            @if ( session('status'))
                <div class="alert alert-dark-{{session('type')}} alert-dismissible fade show">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    {!! session('status') !!}<br>
                </div>
            @endif

            @if( session('error'))
                <div class="alert alert-dark-warning alert-dismissible fade show">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    {!! session('error') !!}
                </div>
            @endif

            {!! Form::open(['route' => 'directs.getstatistic']) !!}
            <div class="input-daterange input-group" id="datepicker-range">
                {!! Form::text('start', null, ['class' =>  'form-control', 'autocomplete' => 'off']) !!}
                <div class="input-group-prepend">
                    <span class="input-group-text">по</span>
                </div>
                {!! Form::text('end', null, ['class' =>  'form-control', 'autocomplete' => 'off']) !!}
            </div>
            <br>
            {!! Form::submit('Запросить статистику', ['class' => 'btn btn-outline-success']) !!}

            {!! Form::close() !!}

        </div>
    </div>



@endsection

resources/views/admin/yandex/direct/Formcreatedirect.blade.php
@extends('layouts.app')

@section('styles')

@endsection

@section('scripts')

@endsection

@section('content')
    <div class="card mb-4">

        <h6 class="card-header">
            Добавление нового аккаунта </h6>
        <div class="card-body">
            @if ( session('status'))
                <div class="alert alert-dark-{{session('type')}} alert-dismissible fade show">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    {{ session('status') }}<br>
                </div>
            @endif
            {!! Form::open(['route' => 'directs.formcreate']) !!}
            <div class="form-group">
                {!! Form::label('token_name', 'Название аккаунта:') !!}
                {!! Form::text('token_name', null, ['class' =>  $errors->has('token_name') ? 'form-control is-invalid' : 'form-control']) !!}
                @if ($errors->has('token_name'))
                    <small class="invalid-feedback">
                        {{ $errors->first('token_name') }}
                    </small>
                @endif
            </div>
            <div class="form-group">
                {!! Form::label('user_login', 'Логин пользователя:') !!}
                {!! Form::text('user_login', null, ['class' =>  $errors->has('user_login') ? 'form-control is-invalid' : 'form-control']) !!}
                @if ($errors->has('user_login'))
                    <small class="invalid-feedback">
                        {{ $errors->first('user_login') }}
                    </small>
                @endif
            </div>

            {!! Form::submit('Сохранить', ['class' => 'btn btn-outline-success']) !!}

            {!! Form::close() !!}

        </div>
    </div>



@endsection

resources/views/admin/yandex/direct/Formrefreshdirect.blade.php
@extends('layouts.app')

@section('styles')

@endsection

@section('scripts')

@endsection

@section('content')
    <div class="card mb-4">
        <h6 class="card-header">
            Перенос рекламы на новый аккаунт </h6>
        <div class="card-body">

            @if( session('new_token_id'))
                <div class="alert alert-dark-danger alert-dismissible fade show">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    На данном этапе всё готово к началу переноса кампаний.<br>
                    Внимательно проверьте данные:<br>
                    Рекламная капмания переносится с аккаунта: {{ session('old_user_name') }}@yandex.ru<br>
                    В аккаунт: {{ session('new_user_login') }}@yandex.ru<br>
                </div>

                {!! Form::open(['route' => 'directs.startrefresh']) !!}


                <div class="form-group">
                    {!! Form::hidden('old_token_id', session('old_token_id')) !!}
                </div>

                <div class="form-group">
                    {!! Form::label('site_link', 'Ссылка на сайт (с указанием протокола):') !!}
                    {!! Form::text('site_link', null, ['class' =>  $errors->has('site_link') ? 'form-control is-invalid' : 'form-control']) !!}
                    @if ($errors->has('site_link'))
                        <small class="invalid-feedback">
                            {{ $errors->first('site_link') }}
                        </small>
                    @endif
                </div>

                <div class="form-group">
                    {!! Form::hidden('new_token_id', session('new_token_id')) !!}
                </div>

                {!! Form::submit('Перенести кампанию.', ['class' => 'btn btn-outline-success']) !!}

                {!! Form::close() !!}
            @else
                <div class="alert alert-dark-primary alert-dismissible fade show">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    Внимание! На данном этапе вы должны быть авторизованы под новым пользователем в вашем яндексе.
                </div>

                {!! Form::open(['route' => 'directs.refresh']) !!}
                <div class="form-group">
                    {!! Form::label('new_user_login', 'Логин нового пользователя:') !!}
                    {!! Form::text('new_user_login', null, ['class' =>  $errors->has('new_user_login') ? 'form-control is-invalid' : 'form-control']) !!}
                    @if ($errors->has('new_user_login'))
                        <small class="invalid-feedback">
                            {{ $errors->first('new_user_login') }}
                        </small>
                    @endif
                </div>

                <div class="form-group">
                    {!! Form::hidden('step_two', '2') !!}
                </div>
                <div class="form-group">
                    {!! Form::hidden('old_token_id', $userdata['token_id']) !!}
                </div>
                <div class="form-group">
                    {!! Form::hidden('old_token_name', $userdata['token_name']) !!}
                </div>
                <div class="form-group">
                    {!! Form::hidden('old_token', $userdata['token']) !!}
                </div>
                <div class="form-group">
                    {!! Form::hidden('old_user_login', $userdata['user_login']) !!}
                </div>

                {!! Form::submit('Начать процесс переноса', ['class' => 'btn btn-outline-success']) !!}

                {!! Form::close() !!}
            @endif
        </div>
    </div>



@endsection