routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([
  'middleware' => 'auth',
  'namespace' => 'Admin',
  'prefix' => 'system/role',
  'as' => 'roles.',
], function () {
    Route::get('/', ['as' => 'show', 'uses' => 'AdminRoleController@index']);

    Route::get('/create',
      ['as' => 'formcreate', 'uses' => 'AdminRoleController@showformcreate']);

    Route::post('/create',
      ['as' => 'create', 'uses' => 'AdminRoleController@create']);

    Route::get('/update/{id}',
      ['as' => 'formupdate', 'uses' => 'AdminRoleController@showformupdate']);

    Route::post('/update',
      ['as' => 'update', 'uses' => 'AdminRoleController@update']);

    Route::post('/delete',
      ['as' => 'delete', 'uses' => 'AdminRoleController@delete']);
});

Route::group([
  'middleware' => 'auth',
  'namespace' => 'Admin',
  'prefix' => 'system/permission',
  'as' => 'permissions.',
], function () {
    Route::get('/',
      ['as' => 'show', 'uses' => 'AdminPermissionController@index']);

    Route::get('/create',
      [
        'as' => 'formcreate',
        'uses' => 'AdminPermissionController@showformcreate',
      ]);

    Route::post('/create',
      ['as' => 'create', 'uses' => 'AdminPermissionController@create']);

    Route::get('/update/{id}',
      [
        'as' => 'formupdate',
        'uses' => 'AdminPermissionController@showformupdate',
      ]);

    Route::post('/update',
      ['as' => 'update', 'uses' => 'AdminPermissionController@update']);

    Route::post('/delete',
      ['as' => 'delete', 'uses' => 'AdminPermissionController@delete']);
});

Route::group([
  'middleware' => 'auth',
  'namespace' => 'Admin',
  'prefix' => 'system/user',
  'as' => 'users.',
], function () {
    Route::get('/',
      ['as' => 'show', 'uses' => 'AdminUserController@index']);

    //    Route::get('/create',
    //      [
    //        'as' => 'formcreate',
    //        'uses' => 'AdminUserController@showformcreate',
    //      ]);
    //
    //    Route::post('/create',
    //      ['as' => 'create', 'uses' => 'AdminUserController@create']);

    Route::get('/update/{id}',
      [
        'as' => 'formupdate',
        'uses' => 'AdminUserController@showformupdate',
      ]);

    Route::post('/update',
      ['as' => 'update', 'uses' => 'AdminUserController@update']);

    Route::post('/delete',
      ['as' => 'delete', 'uses' => 'AdminUserController@delete']);
});

Route::group([
  'middleware' => 'auth',
  'namespace' => 'Admin',
  'prefix' => 'yandex/webmaster',
  'as' => 'webmasters.',
], function () {
    Route::get('/',
      ['as' => 'show', 'uses' => 'AdminYandexWebmasterController@index']);

    Route::get('/create',
      [
        'as' => 'formcreate',
        'uses' => 'AdminYandexWebmasterController@showformcreate',
      ]);

    Route::post('/create',
      ['as' => 'create', 'uses' => 'AdminYandexWebmasterController@create']);


    //    Route::get('/update/{id}',
    //      [
    //        'as' => 'formupdate',
    //        'uses' => 'AdminUserController@showformupdate',
    //      ]);
    //
    //    Route::post('/update',
    //      ['as' => 'update', 'uses' => 'AdminUserController@update']);
    //
    Route::post('/delete',
      ['as' => 'delete', 'uses' => 'AdminYandexWebmasterController@delete']);

    Route::get('/callback',
      [
        'as' => 'callback',
        'uses' => 'AdminYandexWebmasterController@callback',
      ]);
});
Route::group([
  'middleware' => 'auth',
  'as' => 'home',
], function () {
    Route::get('/', 'HomeController@index')->name('home');
});

Route::group([
  'middleware' => 'auth',
  'namespace' => 'Admin',
  'prefix' => 'yandex/direct',
  'as' => 'directs.',
], function () {
    Route::get('/',
      ['as' => 'show', 'uses' => 'AdminYandexDirectController@index']);

    Route::get('/create',
      [
        'as' => 'formcreate',
        'uses' => 'AdminYandexDirectController@showformcreate',
      ]);

    Route::post('/create',
      ['as' => 'create', 'uses' => 'AdminYandexDirectController@create']);

    Route::post('/refresh',
      [
        'as' => 'refresh',
        'uses' => 'AdminYandexDirectController@showformrefresh',
      ]);

    Route::post('/refresh-token',
      [
        'as' => 'refresh.token',
        'uses' => 'AdminYandexDirectController@refreshToken',
      ]);

    Route::get('/check-refresh',
      [
        'as' => 'check.refresh',
        'uses' => 'AdminYandexDirectController@checkshowformrefresh',
      ]);

    Route::post('/startrefresh',
      [
        'as' => 'startrefresh',
        'uses' => 'AdminYandexDirectController@refresh',
      ]);
    //    Route::get('/update/{id}',
    //      [
    //        'as' => 'formupdate',
    //        'uses' => 'AdminUserController@showformupdate',
    //      ]);
    //
    //    Route::post('/update',
    //      ['as' => 'update', 'uses' => 'AdminUserController@update']);
    //
    Route::post('/archive',
      ['as' => 'archive', 'uses' => 'AdminYandexDirectController@archive']);

    Route::get('/getarchive',
      ['as' => 'getarchive', 'uses' => 'AdminYandexDirectController@index']);

    Route::get('/statistics',
      [
        'as' => 'statistics',
        'uses' => 'AdminYandexDirectController@statistics',
      ]);

    Route::post('/getstatistic',
      [
        'as' => 'getstatistic',
        'uses' => 'AdminYandexDirectController@getstatistic',
      ]);

    Route::get('/callback',
      [
        'as' => 'callback',
        'uses' => 'AdminYandexDirectController@callback',
      ]);
});



Auth::routes();

app/Role.php
<?php

namespace App;

use Zizaco\Entrust\EntrustRole;
class Role extends EntrustRole
{

    protected $fillable = ['name', 'display_name', 'description'];
}

resources/views/admin/system/roles/Formcreateroles.blade.php
@extends('layouts.app')

@section('styles')
@endsection

@section('scripts')
@endsection

@section('content')
    <div class="card mb-4">
        <h6 class="card-header">
            Добавление роли </h6>
        <div class="card-body">
            {!! Form::open(['route' => 'roles.create']) !!}
            <div class="form-group">
                {!! Form::label('name', 'Название роли:') !!}
                {!! Form::text('name', null, ['class' =>  $errors->has('name') ? 'form-control is-invalid' : 'form-control']) !!}
                @if ($errors->has('name'))
                    <small class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </small>
                @endif
            </div>

            <div class="form-group">
                {!! Form::label('display_name', 'Отображаемое имя роли:') !!}
                {!! Form::text('display_name', null, ['class' => $errors->has('display_name') ? 'form-control is-invalid' : 'form-control']) !!}
                @if ($errors->has('display_name'))
                    <small class="invalid-feedback">
                        {{ $errors->first('display_name') }}
                    </small>
                @endif
            </div>

            <div class="form-group">
                {!! Form::label('description', 'Описание роли:') !!}
                {!! Form::text('description', null, ['class' => $errors->has('description') ? 'form-control is-invalid' : 'form-control']) !!}
                @if ($errors->has('description'))
                    <small class="invalid-feedback">
                        {{ $errors->first('description') }}
                    </small>
                @endif
            </div>


            @foreach($permissions as $permission)
                <div class="form-group">
                    <label class="switcher switcher-success">
                        {!! Form::checkbox('permission[]', $permission->id, false, ['class' => 'switcher-input']) !!}
                        <span class="switcher-indicator">
                            <span class="switcher-yes">
                                <span class="ion ion-md-checkmark"></span>
                            </span>
                            <span class="switcher-no">
                                <span class="ion ion-md-close"></span>
                            </span>
                        </span>
                        {!! Form::label('description', $permission->display_name, ['class' => 'switcher-label']) !!}
                    </label>
                </div>
            @endforeach

            {!! Form::submit('Сохранить', ['class' => 'btn btn-outline-success']) !!}

            {!! Form::close() !!}

        </div>
    </div>



@endsection

resources/views/admin/system/roles/Formupdateroles.blade.php
@extends('layouts.app')

@section('styles')
@endsection

@section('scripts')
@endsection

@section('content')
    <div class="card mb-4">
        <h6 class="card-header">
            Редактирование роли </h6>
        <div class="card-body">
            {!! Form::open(['route' => 'roles.update']) !!}

            {!! Form::hidden('roleid', $role->id) !!}

            <div class="form-group">
                {!! Form::label('name', 'Переменная:') !!}
                {!! Form::text('name', $role->name, ['class' =>  $errors->has('name') ? 'form-control is-invalid' : 'form-control']) !!}
                @if ($errors->has('name'))
                    <small class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </small>
                @endif
            </div>

            <div class="form-group">
                {!! Form::label('display_name', 'Отображаемое имя роли:') !!}
                {!! Form::text('display_name', $role->display_name, ['class' => $errors->has('display_name') ? 'form-control is-invalid' : 'form-control']) !!}
                @if ($errors->has('display_name'))
                    <small class="invalid-feedback">
                        {{ $errors->first('display_name') }}
                    </small>
                @endif
            </div>

            <div class="form-group">
                {!! Form::label('description', 'Описание роли:') !!}
                {!! Form::text('description', $role->description, ['class' => $errors->has('description') ? 'form-control is-invalid' : 'form-control']) !!}
                @if ($errors->has('description'))
                    <small class="invalid-feedback">
                        {{ $errors->first('description') }}
                    </small>
                @endif
            </div>


            @foreach($permissions as $permission)
                <div class="form-group">
                    <label class="switcher switcher-success">
                        {!! Form::checkbox('permission[]', $permission->id, in_array($permission->id,$role_permissions) ? true : false, ['class' => 'switcher-input']) !!}
                        <span class="switcher-indicator">
                            <span class="switcher-yes">
                                <span class="ion ion-md-checkmark"></span>
                            </span>
                            <span class="switcher-no">
                                <span class="ion ion-md-close"></span>
                            </span>
                        </span>
                        {!! Form::label('description', $permission->display_name, ['class' => 'switcher-label']) !!}
                    </label>
                </div>
            @endforeach

            {!! Form::submit('Сохранить', ['class' => 'btn btn-outline-success']) !!}

            {!! Form::close() !!}

        </div>
    </div>



@endsection

resources/views/admin/system/roles/Role.blade.php
@extends('layouts.app')
@section('styles')
    <!-- Tables -->
    <link rel="stylesheet" href="{{ mix('/vendor/libs/datatables/datatables.css') }}">

    <!-- SweetAlerts -->
    <link rel="stylesheet" href="{{ mix('/vendor/libs/bootstrap-sweetalert/bootstrap-sweetalert.css') }}">
@endsection

@section('scripts')
    <!-- Tables -->
    <script src="{{ mix('/vendor/libs/datatables/datatables.js') }}"></script>
    <script src="{{ mix('/js/tables_datatables.js') }}"></script>
    <!-- SweetAlerts -->
    <script src="{{ mix('/vendor/libs/bootbox/bootbox.js') }}"></script>
    <script src="{{ mix('/vendor/libs/bootstrap-sweetalert/bootstrap-sweetalert.js') }}"></script>

    <script src="{{ mix('/js/ui_modals.js') }}"></script>
@endsection



@section('content')
    <h4 class="d-flex justify-content-between align-items-center w-100 font-weight-bold py-3 mb-4">
        <div>Роли</div>
        @permission('create-roles')
        <a href="{{ URL::route('roles.formcreate') }}" class="btn btn-sm btn-outline-success">
            <span class="ion ion-md-add"></span>&nbsp; Добавить роль
        </a>
        @endpermission
    </h4>


    @if ( session('status'))
        <div class="alert alert-dark-{{ session('type') }} alert-dismissible fade show">
            <button type="button" class="close" data-dismiss="alert">×</button>
            {{ session('status') }}
        </div>
    @endif
    <div class="card">
        <h6 class="card-header fc-left">
            Все существующие роли </h6>

        <div class="card-datatable table-responsive">
            <table class="datatables-demo table table-striped table-bordered">
                <thead>
                <tr>
                    <th>Название</th>
                    <th>Переменная</th>
                    <th>Дата создания / обновления</th>
                    <th>Статус</th>
                    <th>Опции</th>
                </tr>
                </thead>
                <tbody>
                @foreach ($roles as $role)
                    <tr class="odd gradeX" id="{{ $role->id }}">
                        <td>
                            {{ $role->display_name }}
                        </td>
                        <td>
                            {{ $role->name }}
                        </td>
                        <td>
                            <small>@if($role->updated_at == $role->created_at)
                                    Создана {{ $role->created_at }}
                                @else
                                    Обновлена {{ $role->updated_at }}
                                @endif
                            </small>
                        </td>
                        <td>

                            @forelse ($role->users as $user)
                                <span class="badge badge-outline-success">Используется</span>
                                @break
                            @empty
                                <span class="badge badge-outline-danger">Не Используется</span>
                            @endforelse
                        </td>

                        <td>

                            @permission('update-roles')
                            <a href="{{ route('roles.formupdate', ['id' => $role->id])  }}"
                               class="btn btn-xs btn-outline-success btn-sm"><i class="fa fa-pencil"></i> Правка
                            </a>
                            @endpermission

                            @permission('delete-roles')
                            <input type="hidden" id="token" value="<?php echo csrf_token(); ?>">
                            <button class="btn btn-xs btn-outline-danger delete" data-element-id="{{ $role->id }}"
                                    data-method-post="delete" onclick="return false;"><i class="fa fa-times"></i>
                                Удалить
                            </button>
                            @endpermission

                        </td>
                    </tr>

                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection